# Generated by Django 5.2 on 2025-06-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalized_Learning_App', '0009_friendrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
