# Generated by Django 5.2 on 2025-05-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personalized_Learning_App', '0005_courseprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseProgress',
        ),
    ]
